import slackIcon from '../../../assets/images/slack.svg';

export const membersTableData = [
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Dias',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
    {
        name: 'Randy Diaso',
        platform: {
            img1: slackIcon,
            img2: slackIcon,
        },
        tags: '---',
        lastActivity: '30 April 2022',
        organization: 'Neoito',
        location: 'Texas',
        email: 'randy123@mail.com',
    },
];

export const dummyDragData = [
    {
        name: 'Hari',
        id: '1',
    },
    {
        name: 'Amal',
        id: '2',
    },
    {
        name: 'Harik',
        id: '3',
    },
    {
        name: 'Amalk',
        id: '4',
    },
]